data:
  # Chemins Kaggle
  raw_dir: /kaggle/input/prasoonkottarathil/face-mask-lite-dataset
  processed_dir: /kaggle/working/datasets/processed
  scale_factor: 4
  mask_type: surgical
  image_size: 256

training:
  epochs: 100
  batch_size: 8
  lr_g: 0.0002
  lr_d: 0.0002
  lambda_l1: 100.0
  lambda_arcface: 1.0

model:
  features_g: 64

logging:
  tensorboard_dir: /kaggle/working/results/tensorboard
  checkpoint_dir: /kaggle/working/models/checkpoints
  wandb_project: face-unmasking