data:
  raw_dir: /kaggle/input/datasets/arnaud58/flickrfaceshq-dataset-ffhq  # FFHQ source
  processed_dir: /kaggle/working/face_dataset  # ← Sortie du preprocessing
  split: train
  scale_factor: 4
  scale_factors: [2, 4, 8]
  mask_type: surgical
  mask_types: [surgical, fabric, n95, black, white, colored]
  image_size: 256

training:
  epochs: 100
  batch_size: 8
  lr_g: 0.0002
  lr_d: 0.0002
  lambda_l1: 100.0
  lambda_arcface: 1.0

model:
  features_g: 64

logging:
  tensorboard_dir: /kaggle/working/results/tensorboard
  checkpoint_dir: /kaggle/working/models/checkpoints
  wandb_project: face-unmasking